language: objective-c
podfile: Example/Podfile

before_install:
    - gem install cocoapods --quiet
    - sleep 20

script:
    - xctool -workspace Example/SwiftArmyExample.xcworkspace -sdk iphonesimulator -scheme SwiftArmyExampleTests -sdk iphonesimulator8.1 build test
