language: objective-c
osx_image: beta-xcode6.3
podfile: Example/Podfile

before_install:
    - gem install cocoapods --quiet
    - sleep 20

script:
    - xctool -workspace Example/SwiftArmyExample.xcworkspace -sdk iphonesimulator -scheme SwiftArmyExampleTests -sdk iphonesimulator8.3 build test
